# Generated by Django 4.1 on 2024-05-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='Picture',
            new_name='picture',
        ),
    ]
